import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { formatDistanceToNow } from "date-fns";
import type { CreatorPost, User } from "@shared/schema";
import { CheckCircle, TrendingUp, TrendingDown } from "lucide-react";

type PostWithCreator = CreatorPost & { creator: User };

interface PostFeedProps {
  botId: string;
}

export function PostFeed({ botId }: PostFeedProps) {
  const { data: posts = [], isLoading } = useQuery<PostWithCreator[]>({
    queryKey: ["/api/bots", botId, "posts"],
  });

  if (isLoading) {
    return (
      <div className="space-y-4">
        {[1, 2, 3].map((i) => (
          <Card key={i} className="hover-elevate">
            <CardHeader className="flex flex-row items-center gap-4 space-y-0 pb-4">
              <div className="h-10 w-10 rounded-full bg-muted/50 animate-pulse" />
              <div className="space-y-2">
                <div className="h-4 w-32 bg-muted/50 rounded animate-pulse" />
                <div className="h-3 w-24 bg-muted/50 rounded animate-pulse" />
              </div>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                <div className="h-4 w-full bg-muted/50 rounded animate-pulse" />
                <div className="h-4 w-3/4 bg-muted/50 rounded animate-pulse" />
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    );
  }

  if (posts.length === 0) {
    return (
      <Card>
        <CardContent className="py-12 text-center">
          <p className="text-muted-foreground">No posts yet. Check back later for updates from the creator.</p>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      {posts.map((post) => (
        <Card key={post.id} className="hover-elevate" data-testid={`post-card-${post.id}`}>
          <CardHeader className="flex flex-row items-center gap-4 space-y-0 pb-4">
            <Avatar className="h-10 w-10">
              <AvatarImage src={post.creator.profileImageUrl || undefined} />
              <AvatarFallback>
                {post.creator.firstName?.[0]}
                {post.creator.lastName?.[0]}
              </AvatarFallback>
            </Avatar>
            <div className="flex-1">
              <div className="flex items-center gap-2">
                <span className="font-medium" data-testid={`post-creator-${post.id}`}>
                  {post.creator.firstName} {post.creator.lastName}
                </span>
                <CheckCircle className="h-4 w-4 text-primary" />
              </div>
              <p className="text-sm text-muted-foreground" data-testid={`post-timestamp-${post.id}`}>
                {formatDistanceToNow(new Date(post.createdAt), { addSuffix: true })}
              </p>
            </div>
            {post.isAutoGenerated && (
              <Badge variant="secondary" data-testid={`post-auto-badge-${post.id}`}>
                Auto-generated
              </Badge>
            )}
            {post.postType === "chart" && (
              <Badge variant="outline" data-testid={`post-type-badge-${post.id}`}>
                <TrendingUp className="h-3 w-3 mr-1" />
                Chart
              </Badge>
            )}
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-sm leading-relaxed whitespace-pre-wrap" data-testid={`post-content-${post.id}`}>
              {String(post.content)}
            </p>
            
            {post.chartData ? (
              <div className="rounded-lg border bg-muted/30 p-4" data-testid={`post-chart-${post.id}`}>
                <div className="flex items-center justify-between text-sm">
                  <span className="font-medium">Performance Snapshot</span>
                  <span className="text-muted-foreground">
                    Chart data included
                  </span>
                </div>
              </div>
            ) : null}
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
